### ISSUE TITLE
datasetid

### ISSUE THREAD

**Issue by umang4002** [yaoppeng/U-Net_v2#1]
python /path/to/U-Net_v2/run/run_training.py dataset_id 2d 0 --no-debug -tr ISICTrainer --c 
What is datasetid here ? 
For example if I am using ISIC 2017. And is this command should be run in script or can be directly run in jupyter notebook?

**Comment by yaoppeng** [comment]
When you download the dataset, you create a folder; for instance, Dataset122_ISIC. In this case, "122" is the dataset ID. You may refer to nnUNet for more details about this.
