### ISSUE TITLE
Question on #11 issue

### ISSUE THREAD

**Issue by SwimmingLiu** [yaoppeng/U-Net_v2#12]
Hello, Sir.  I have some question on a closed issue #11 
I wonder if there is difference in two downsamping ways that "Conv with stride=2" and "MaxPool"? And "avoid too many downsamplings" is equal to "make Unet shallower" ?

**Comment by yaoppeng** [comment]
Strided Conv is a parameterized downsampling, but it does not necessarily perform better than MaxPool; it depends on the data (deep learning mystery). You may use a deeper UNet, but it may not contribute too much to the performance if the target object is very small. But, you have to use the shallow-level features for small object segmentation.

**Comment by SwimmingLiu** [comment]
Aright, thanks for your reply.
