### ISSUE TITLE
Use of Optimizer 

### ISSUE THREAD

**Issue by yeerwen** [yaoppeng/U-Net_v2#13]
Hi, 

Great job on your work!  I've noticed a few discrepancies between the paper and the implementation in your code. Specifically, the optimizer mentioned in the paper is Adam, but in your code, it appears to be SGD (as seen in line 102 of polypTrainer.py). Could you please clarify which optimizer is the correct one used in your research?

Thank you in advance for your response.

Best regards,
Yiwen

**Comment by yaoppeng** [comment]
For polyp segmentation, please refer to the folder 'PolypSeg,' which used multi-scale training. I tried Adam, AdamW, SGD, and other optimizers. For polyp segmentation, Adam and AdamW perform a little better than SGD. For ISIC, they perform the same.

**Comment by yeerwen** [comment]
Thanks for the quick reply.
