### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by xiaoaleiBLUE** [yaoppeng/U-Net_v2#4]
Download the training dataset from google drive and testing dataset from google drive
run the training using the following command:python /path/to/U-Net_v2/PolypSeg/Train.py. An error occurred in the following statement: P1, P2= model(images)
ValueError: too many values to unpack (expected 2)

**Comment by Wxy19992** [comment]
您好，我现在和你遇到一样的问题，这个您怎么解决的？
